sudo: required
language: bash

services:
  - docker

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t zabbix-server .
  - docker push $DOCKER_USERNAME/zabbix-server-ta
