sudo: required
language: bash

services:
  - docker

script:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t zabbix-server
  - docker push "$DOCKER_USERNAME"/zabbix-server-ta
