sudo: required
language: bash

services:
  - docker

script:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  - docker build -t zabbix-server .
  - docker push $DOCKER_USERNAME/zabbix-server-ta
